### ISSUE TITLE
第 64 题：ALB和SLB

### ISSUE THREAD

**Issue by hezhengjie** [Libra-studio/One-question-every-week#64]
简单介绍下ALB和SLB

**Comment by cloudmoonocus** [comment]
ALB（Application Load Balancer）和SLB（Server Load Balancer）是负载均衡器的两种类型，它们用来分配客户端请求到后端服务器，以提高应用程序的可用性和扩展性。

ALB（Application Load Balancer）：
ALB是一种应用层负载均衡器，它工作在OSI模型的第七层，也就是应用层。ALB主要用于HTTP和HTTPS流量的负载均衡，并且提供了高级的请求路由功能，比如基于内容的路由（例如URL路径或域名），请求头信息，HTTP方法等。这使得ALB特别适合处理复杂的应用程序体系结构，如微服务和容器化服务。ALB支持SSL/TLS终止，可以处理加密的流量，并且能够执行HTTP/2和WebSocket协议的负载均衡。

SLB（Server Load Balancer）：
SLB通常指的是工作在OSI模型的第四层的负载均衡器，也称为传输层负载均衡器。它主要基于TCP和UDP协议，对传入请求进行负载均衡，不像ALB那样关心应用层内容。SLB通常更关注网络连接的持久性和性能，而不是具体的应用程序逻辑。SLB可以非常高效地将流量分发到服务器池中，通常用于简单的负载分发场景，如将大量的并发TCP连接分散到多个服务器上。

不同的云服务提供商可能会为这些服务提供不同的名称。例如，在Amazon Web Services (AWS)中，ALB和SLB分别对应于Application Load Balancer和Classic Load Balancer。而在阿里云中，SLB对应于阿里云的负载均衡服务，它同时支持四层和七层的负载均衡功能。在选择使用ALB还是SLB时，需要根据应用程序的具体需求和架构来决定最适合的负载均衡器类型。
